config/routes.rb
Rails.application.routes.default_url_options[:host] = Rails.application.credentials.dig(:host)
Rails.application.routes.default_url_options[:port] = Rails.application.credentials.dig(:port)

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_for :users

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resource :auth
      resources :users
      resources :notification_tokens, only: :create
    end
  end

  authenticated :user, lambda { |u| u.admin? } do
    namespace :admin do
      resources :comments, only: [:index, :destroy]
    end
  end

  authenticated :user do
    resource :onboarding, only: [:show, :create]

    resources :activities do
      resources :comments, only: [:create, :update], module: :activities do
        resource :reports, only: [:create], module: :comments
      end
      resources :participants, only: [:index, :create, :destroy], module: :activities
    end
    resources :athletes, only: [:show]
    namespace :cities do
      resource :autocomplete, only: [:show]
    end
    resource :dashboard, only: [:show]
    resource :profile, only: [:show, :edit, :update, :destroy]
    resources :sports

    root to: "dashboards#show", as: :user_root
  end

  unauthenticated :user do
    get "/activities", to: "pages#activities"
    get "/profile", to: "pages#profile"
  end

  get "/privacy", to: "pages#privacy"
  get "/terms", to: "pages#terms"

  root to: "pages#home"
end

app/models/sport.rb
# == Schema Information
#
# Table name: sports
#
#  id         :uuid             not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Sport < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_name, against: :name, using: { tsearch: { prefix: true } }

  has_one_attached :icon
  has_one_attached :cover_photo
  has_many :activities, dependent: :destroy
  has_many :users, dependent: :nullify

  def future_activities_for(user)
    activities.near([user.latitude, user.longitude], 10, units: :km).future.order(starts_at: :asc)
  end
end

app/controllers/sports/application_controller.rb
# frozen_string_literal: true

class Sports::ApplicationController < ApplicationController
  before_action :set_sport

  private

  def set_sport
    @sport = Sport.find(params[:sport_id])
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  before_action :set_sport, only: %i[ show edit update destroy ]

  # GET /sports or /sports.json
  def index
    if params[:q] && params[:q].present?
      @pagy, @sports = pagy(Sport.search_by_name(params[:q]))
    else
      @pagy, @sports = pagy(Sport.all)
    end

    authorize @sports
  end

  # GET /sports/1 or /sports/1.json
  def show
    @future_activities = @sport.future_activities_for(current_user)
  end

  # GET /sports/new
  def new
    @sport = Sport.new
    authorize @sport
  end

  # GET /sports/1/edit
  def edit
  end

  # POST /sports or /sports.json
  def create
    @sport = Sport.new(sport_params)
    authorize @sport

    respond_to do |format|
      if @sport.save
        format.html { redirect_to sport_url(@sport), notice: "Sport was successfully created." }
        format.json { render :show, status: :created, location: @sport }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sports/1 or /sports/1.json
  def update
    respond_to do |format|
      if @sport.update(sport_params)
        format.html { redirect_to sport_url(@sport), notice: "Sport was successfully updated." }
        format.json { render :show, status: :ok, location: @sport }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sports/1 or /sports/1.json
  def destroy
    @sport.destroy

    respond_to do |format|
      format.html { redirect_to sports_url, notice: "Sport was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sport
      @sport = Sport.find(params[:id])
      authorize @sport
    end

    # Only allow a list of trusted parameters through.
    def sport_params
      params.require(:sport).permit(:name)
    end
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/sports/_form.html.erb
<%= form_with(model: sport, class: "contents") do |form| %>
  <% if sport.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(sport.errors.count, "error") %> prohibited this sport from being saved:</h2>

      <ul>
        <% sport.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/sports/_sport.html.erb
<%= link_to sport do %>
  <div class="relative border-b border-gray-200">
    <ul role="list" class="relative z-0 divide-y divide-gray-200">
      <li>
        <div class="relative flex items-center space-x-3 px-6 py-5 hover:bg-gray-50">
          <div class="flex-shrink-0">
            <img class="h-10 w-10 rounded-full" src="https://cdn-icons-png.flaticon.com/512/33/33838.png" alt="">
          </div>
          <div class="min-w-0 flex-1">
            <%= link_to sport, class: "focus:outline-none" do %>
              <!-- Extend touch target to entire panel -->
              <span class="absolute inset-0" aria-hidden="true"></span>
              <p class="font-xl text-gray-900 font-semibold"><%= sport.name %></p>
            <% end %>
          </div>
        </div>
      </li>
    </ul>
  </div>
<% end %>

app/views/sports/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing sport</h1>

  <%= render "form", sport: @sport %>

  <%= link_to "Show this sport", @sport, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to sports", sports_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/sports/index.html.erb
<% content_for :header_title, "Les sports" %>
<% content_for :header_logo, "logo.png" %>
<% content_for :header_back_link, dashboard_path %>

<% content_for :header_right_nav do %>
  <div data-action="click->header#toggleSearchBar" class="cursor-pointer">
    <%= inline_svg_tag "svg/search.svg", class: "w-6" %>
  </div>
<% end %>

<% content_for :header_main do %>
  <%= form_with(url: sports_path, method: :get, class: "text-black w-3/4 mx-auto mt-4 hidden", data: { "header-target": "searchBar" }) do |form| %>
    <div class="relative mt-1 flex items-center">
      <%= form.text_field :q, class:"y-form",  data: { "header-target": "searchInput" } , placeholder: "Rechercher..." %>
      <div class="absolute inset-y-0 right-0 flex py-1.5 pr-1.5">
        <button class="inline-flex items-center border-1 border-l px-2 font-sans text-sm font-medium text-gray-400">
          <%= inline_svg_tag "svg/search.svg", class: "w-6" %>
        </button>
      </div>
    </div>
  <% end %>
<% end %>

<% content_for :main do %>
  <article>
    <!-- Profile header -->
    <div>
      <div>
        <img class="h-32 w-full object-cover lg:h-48" src="https://images.unsplash.com/photo-1444628838545-ac4016a5418a?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80" alt="">
      </div>
      <div class="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8">
        <div class="-mt-12 sm:-mt-16 sm:flex sm:items-end sm:space-x-5">
          <div class="flex">
            <img class="h-24 w-24 rounded-full ring-4 ring-white sm:h-32 sm:w-32" src="https://images.unsplash.com/photo-1463453091185-61582044d556?ixlib=rb-=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=8&w=1024&h=1024&q=80" alt="">
          </div>
          <div class="mt-6 sm:flex sm:min-w-0 sm:flex-1 sm:items-center sm:justify-end sm:space-x-6 sm:pb-1">
            <div class="mt-6 min-w-0 flex-1 sm:hidden 2xl:block">
              <h1 class="truncate text-2xl font-bold text-gray-900">Ricardo Cooper</h1>
            </div>
            <div class="justify-stretch mt-6 flex flex-col space-y-3 sm:flex-row sm:space-y-0 sm:space-x-4">
              <button type="button" class="inline-flex justify-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-pink-500 focus:ring-offset-2">
                <!-- Heroicon name: mini/envelope -->
                <svg class="-ml-1 mr-2 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path d="M3 4a2 2 0 00-2 2v1.161l8.441 4.221a1.25 1.25 0 001.118 0L19 7.162V6a2 2 0 00-2-2H3z" />
                  <path d="M19 8.839l-7.77 3.885a2.75 2.75 0 01-2.46 0L1 8.839V14a2 2 0 002 2h14a2 2 0 002-2V8.839z" />
                </svg>
                <span>Message</span>
              </button>
              <button type="button" class="inline-flex justify-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-pink-500 focus:ring-offset-2">
                <!-- Heroicon name: mini/phone -->
                <svg class="-ml-1 mr-2 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path fill-rule="evenodd" d="M2 3.5A1.5 1.5 0 013.5 2h1.148a1.5 1.5 0 011.465 1.175l.716 3.223a1.5 1.5 0 01-1.052 1.767l-.933.267c-.41.117-.643.555-.48.95a11.542 11.542 0 006.254 6.254c.395.163.833-.07.95-.48l.267-.933a1.5 1.5 0 011.767-1.052l3.223.716A1.5 1.5 0 0118 15.352V16.5a1.5 1.5 0 01-1.5 1.5H15c-1.149 0-2.263-.15-3.326-.43A13.022 13.022 0 012.43 8.326 13.019 13.019 0 012 5V3.5z" clip-rule="evenodd" />
                </svg>
                <span>Call</span>
              </button>
            </div>
          </div>
        </div>
        <div class="mt-6 hidden min-w-0 flex-1 sm:block 2xl:hidden">
          <h1 class="truncate text-2xl font-bold text-gray-900">Ricardo Cooper</h1>
        </div>
      </div>
    </div>

    <!-- Tabs -->
    <div class="mt-6 sm:mt-2 2xl:mt-5">
      <div class="border-b border-gray-200">
        <div class="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8">
          <nav class="-mb-px flex space-x-8" aria-label="Tabs">
            <!-- Current: "border-pink-500 text-gray-900", Default: "border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300" -->
            <a href="#" class="border-pink-500 text-gray-900 whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm" aria-current="page">Profile</a>

            <a href="#" class="border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm">Calendar</a>

            <a href="#" class="border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 whitespace-nowrap py-4 px-1 border-b-2 font-medium text-sm">Recognition</a>
          </nav>
        </div>
      </div>
    </div>

    <!-- Description list -->
    <div class="mx-auto mt-6 max-w-5xl px-4 sm:px-6 lg:px-8">
      <dl class="grid grid-cols-1 gap-x-4 gap-y-8 sm:grid-cols-2">
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">Phone</dt>
          <dd class="mt-1 text-sm text-gray-900">(555) 123-4567</dd>
        </div>

        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">Email</dt>
          <dd class="mt-1 text-sm text-gray-900">ricardocooper@example.com</dd>
        </div>

        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">Title</dt>
          <dd class="mt-1 text-sm text-gray-900">Senior Front-End Developer</dd>
        </div>

        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">Team</dt>
          <dd class="mt-1 text-sm text-gray-900">Product Development</dd>
        </div>

        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">Location</dt>
          <dd class="mt-1 text-sm text-gray-900">San Francisco</dd>
        </div>

        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">Sits</dt>
          <dd class="mt-1 text-sm text-gray-900">Oasis, 4th floor</dd>
        </div>

        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">Salary</dt>
          <dd class="mt-1 text-sm text-gray-900">$145,000</dd>
        </div>

        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">Birthday</dt>
          <dd class="mt-1 text-sm text-gray-900">June 8, 1990</dd>
        </div>

        <div class="sm:col-span-2">
          <dt class="text-sm font-medium text-gray-500">About</dt>
          <dd class="mt-1 max-w-prose space-y-5 text-sm text-gray-900">
            <p>Tincidunt quam neque in cursus viverra orci, dapibus nec tristique. Nullam ut sit dolor consectetur urna, dui cras nec sed. Cursus risus congue arcu aenean posuere aliquam.</p>
            <p>Et vivamus lorem pulvinar nascetur non. Pulvinar a sed platea rhoncus ac mauris amet. Urna, sem pretium sit pretium urna, senectus vitae. Scelerisque fermentum, cursus felis dui suspendisse velit pharetra. Augue et duis cursus maecenas eget quam lectus. Accumsan vitae nascetur pharetra rhoncus praesent dictum risus suspendisse.</p>
          </dd>
        </div>
      </dl>
    </div>

    <!-- Team member list -->
    <div class="mx-auto mt-8 max-w-5xl px-4 pb-12 sm:px-6 lg:px-8">
      <h2 class="text-sm font-medium text-gray-500">Team members</h2>
      <div class="mt-1 grid grid-cols-1 gap-4 sm:grid-cols-2">
        <div class="relative flex items-center space-x-3 rounded-lg border border-gray-300 bg-white px-6 py-5 shadow-sm focus-within:ring-2 focus-within:ring-pink-500 focus-within:ring-offset-2 hover:border-gray-400">
          <div class="flex-shrink-0">
            <img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
          </div>
          <div class="min-w-0 flex-1">
            <a href="#" class="focus:outline-none">
              <span class="absolute inset-0" aria-hidden="true"></span>
              <p class="text-sm font-medium text-gray-900">Leslie Alexander</p>
              <p class="truncate text-sm text-gray-500">Co-Founder / CEO</p>
            </a>
          </div>
        </div>

        <div class="relative flex items-center space-x-3 rounded-lg border border-gray-300 bg-white px-6 py-5 shadow-sm focus-within:ring-2 focus-within:ring-pink-500 focus-within:ring-offset-2 hover:border-gray-400">
          <div class="flex-shrink-0">
            <img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
          </div>
          <div class="min-w-0 flex-1">
            <a href="#" class="focus:outline-none">
              <span class="absolute inset-0" aria-hidden="true"></span>
              <p class="text-sm font-medium text-gray-900">Michael Foster</p>
              <p class="truncate text-sm text-gray-500">Co-Founder / CTO</p>
            </a>
          </div>
        </div>

        <div class="relative flex items-center space-x-3 rounded-lg border border-gray-300 bg-white px-6 py-5 shadow-sm focus-within:ring-2 focus-within:ring-pink-500 focus-within:ring-offset-2 hover:border-gray-400">
          <div class="flex-shrink-0">
            <img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
          </div>
          <div class="min-w-0 flex-1">
            <a href="#" class="focus:outline-none">
              <span class="absolute inset-0" aria-hidden="true"></span>
              <p class="text-sm font-medium text-gray-900">Dries Vincent</p>
              <p class="truncate text-sm text-gray-500">Manager, Business Relations</p>
            </a>
          </div>
        </div>

        <div class="relative flex items-center space-x-3 rounded-lg border border-gray-300 bg-white px-6 py-5 shadow-sm focus-within:ring-2 focus-within:ring-pink-500 focus-within:ring-offset-2 hover:border-gray-400">
          <div class="flex-shrink-0">
            <img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1517841905240-472988babdf9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
          </div>
          <div class="min-w-0 flex-1">
            <a href="#" class="focus:outline-none">
              <span class="absolute inset-0" aria-hidden="true"></span>
              <p class="text-sm font-medium text-gray-900">Lindsay Walton</p>
              <p class="truncate text-sm text-gray-500">Front-end Developer</p>
            </a>
          </div>
        </div>
      </div>
    </div>
  </article>
<% end %>

<!-- Directory list -->
<nav class="flex-1 overflow-y-auto h-[calc(100%-10rem)]" aria-label="Directory">
  <div class="grid grid-cols-2 border-1 border-b border-gray-500">
    <span class="text-center p-2 cursor-pointer">Sport Classiques</span>
    <span class="text-center bg-gray-300 text-gray-500 italic shadow-inner p-2 cursor-pointer">Sport Inédits</span>
  </div>
  <%= render @sports %>
</nav>
<%#== pagy_nav(@pagy) %>

app/views/sports/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New sport</h1>

  <%= render "form", sport: @sport %>

  <%= link_to 'Back to sports', sports_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/sports/show.html.erb
<% content_for :header_title, @sport.name %>
<% content_for :header_background, "logo.png" %>

<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @sport %>

    <% if @future_activities.any? %>
      <h2>Futures activités pour moi</h2>

      <% @future_activities.each do |activity| %>
        <%= render activity %>
      <% end %>
    <% end %>

    <%= link_to "Organiser", new_sport_activity_path(@sport), class: "y-btn y-btn-green bg-blue-500" %>

    <%= link_to 'Edit this sport', edit_sport_path(@sport), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this sport', sport_path(@sport), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to sports', sports_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>