config/routes.rb
Rails.application.routes.default_url_options[:host] = Rails.application.credentials.dig(:host)
Rails.application.routes.default_url_options[:port] = Rails.application.credentials.dig(:port)

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_for :users

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resource :auth
      resources :users
      resources :notification_tokens, only: :create
    end
  end

  authenticated :user, lambda { |u| u.admin? } do
    namespace :admin do
      resources :comments, only: [:index, :destroy]
    end
  end

  authenticated :user do
    resource :onboarding, only: [:show, :create]

    resources :activities do
      resources :comments, only: [:create, :update], module: :activities do
        resource :reports, only: [:create], module: :comments
      end
      resources :participants, only: [:index, :create, :destroy], module: :activities
    end
    resources :athletes, only: [:show]
    namespace :cities do
      resource :autocomplete, only: [:show]
    end
    resource :dashboard, only: [:show]
    resource :profile, only: [:show, :edit, :update, :destroy]
    resources :sports

    root to: "dashboards#show", as: :user_root
  end

  unauthenticated :user do
    get "/activities", to: "pages#activities"
    get "/profile", to: "pages#profile"
  end

  get "/privacy", to: "pages#privacy"
  get "/terms", to: "pages#terms"

  root to: "pages#home"
end

app/controllers/athletes_controller.rb
# frozen_string_literal: true

class AthletesController < ApplicationController
  def show
    @athlete = User.includes(:participations).find(params[:id])
    authorize @athlete, policy_class: AthletePolicy

    @next_organized_activities = @athlete.organized_activities.future
  end
end

app/views/athletes/show.html.erb
<% content_for :header_background, url_for(@athlete.avatar) if @athlete.avatar.attached? %>

<% content_for :header_right_nav do %>
  <% if current_user.eql?(@athlete) %>
    <%= link_to edit_profile_path do %>
      <%= inline_svg_tag "svg/edit.svg", class: "w-6" %>
    <% end %>
  <% end %>
<% end %>

<% content_for :header_main do %>
  <% if current_user.eql?(@athlete) && turbo_native_app? %>
    <div class="-mt-6 flex justify-between">
      <%= link_to edit_profile_path, class: "flex justify-end" do %>
        <%= inline_svg_tag "svg/edit.svg", class: "w-6" %>
      <% end %>

      <%= link_to destroy_user_session_path, data: { turbo_method: :delete } do %>
        <%= inline_svg_tag "svg/logout.svg", class: "w-6" %>
      <% end %>
    </div>
  <% end %>
  <div class="grid grid-cols-3 mt-16 p-2">
    <div class="col-span-2">
      <p class="text-xl font-bold uppercase mb-1"><%= @athlete.nickname %></p>
      <p class="text-xs uppercase mb-2 italic"><%= @athlete.city_name%></p>
      <p class="text-xs uppercase mb-2"><%= @athlete.age %>&nbsp;ans&nbsp;|&nbsp;Abonné le <%= l(@athlete.created_at, format: "%d/%m/%Y") %></p>
      <% if @athlete.sport %>
        <p class="italic p-1 cursor-pointer"><%= @athlete.sport.name %></p>
      <% else %>
        <%= link_to  "+ Ajouter un sport favori", edit_profile_path, class: "bg-white bg-opacity-20 p-1 cursor-pointer" %>
      <% end %>
    </div>
  </div>
<% end %>

<div class="y-card-main space-y-5">
  <div>
    <div class="flex justify-between items-center mb-3">
      <p class="uppercase text-sm font-semibold">Mes évènements</p>
    </div>

    <% if @next_organized_activities.any? %>
      <div class="flex gap-6 snap-x snap-mandatory overflow-x-auto text-black">
        <% @next_organized_activities.each do |next_activity| %>
          <div class="snap-start shrink-0">
            <%= render "activities/event_card", activity: next_activity %>
          </div>
        <% end %>
      </div>
    <% else %>
      <div class="grid grid-cols-2 bg-white border-2 border-dashed border-gray-400 divide-x shadow-md rounded-md overflow-hidden text-center">
        <%= link_to activities_path do %>
          <div class="py-6 flex flex-col items-center justify-center space-x-2">
            <%= inline_svg_tag "svg/plus.svg", class: "w-10" %>
            <span>Rechercher un évènement</span>
          </div>
        <% end %>
        <%= link_to new_activity_path do %>
          <div class="py-6 flex flex-col items-center justify-center space-x-2">
            <%= inline_svg_tag "svg/plus.svg", class: "w-10" %>
            <span>Créer un évènement</span>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

  <% if current_user.eql?(@athlete) %>
    <div class="flex justify-center">
      <%= link_to "Supprimer mon compte", profile_path, data: { turbo_method: :delete, turbo_confirm: "Êtes-vous sûr de vouloir supprimer votre compte ?" }, class: "y-btn y-btn-red" %>
    </div>
  <% end %>

</div>