config/routes.rb
Rails.application.routes.default_url_options[:host] = Rails.application.credentials.dig(:host)
Rails.application.routes.default_url_options[:port] = Rails.application.credentials.dig(:port)

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_for :users

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resource :auth
      resources :users
      resources :notification_tokens, only: :create
    end
  end

  authenticated :user, lambda { |u| u.admin? } do
    namespace :admin do
      resources :comments, only: [:index, :destroy]
    end
  end

  authenticated :user do
    resource :onboarding, only: [:show, :create]

    resources :activities do
      resources :comments, only: [:create, :update], module: :activities do
        resource :reports, only: [:create], module: :comments
      end
      resources :participants, only: [:index, :create, :destroy], module: :activities
    end
    resources :athletes, only: [:show]
    namespace :cities do
      resource :autocomplete, only: [:show]
    end
    resource :dashboard, only: [:show]
    resource :profile, only: [:show, :edit, :update, :destroy]
    resources :sports

    root to: "dashboards#show", as: :user_root
  end

  unauthenticated :user do
    get "/activities", to: "pages#activities"
    get "/profile", to: "pages#profile"
  end

  get "/privacy", to: "pages#privacy"
  get "/terms", to: "pages#terms"

  root to: "pages#home"
end

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div id="sticky-banner" tabindex="-1" class="fixed top-0 left-0 z-50 flex justify-between w-full p-4 border-b border-white bg-yaspeez">
    <div class="flex items-center mx-auto">
      <p class="flex items-center text-sm font-normal text-white">
      <span><%= message %></span>
      </p>
    </div>
    <div class="flex items-center">
      <button data-dismiss-target="#sticky-banner" type="button" class="flex-shrink-0 inline-flex justify-center items-center text-white hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 dark:hover:bg-gray-600 dark:hover:text-white">
        <svg aria-hidden="true" class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
        <span class="sr-only">Fermer</span>
      </button>
    </div>
  </div>
<% end %>

app/views/shared/_follow_card.html.erb
<div class="bg-gray-200 rounded-lg flex snap-x snap-mandatory overflow-x-auto text-black">
  <% 15.times do %>
    <div class="py-4 px-3 snap-start shrink-0">
      <div class="bg-cover bg-center rounded-full w-9 h-9 shrink-0" style="background-image: url(<%= url_for(current_user.avatar) %>);">
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_header.html.erb
<div class="relative rounded-b-2xl bg-yaspeez shadow-inner-lg text-white overflow-hidden">
  <% if turbo_native_app? %>
    <div data-controller="toggle">
      <button id="dropdownDefaultButton" data-action="toggle-nav-bar@window->toggle#toggle toggle#toggle" type="button" class="absolute top-0">
      </button>
      <%= render "shared/menu" %>
    </div>
  <% end %>
  <div class="w-full h-full flex items-center overflow-hidden opacity-50 shrink-0 absolute">
    <%= image_tag yield(:header_background) %>
  </div>
  <div class="relative p-4">
    <% unless turbo_native_app? %>
      <div class="flex justify-between z-20">
        <% if content_for(:header_left_nav) %>
          <%= yield(:header_left_nav) %>
        <% else %>
          <% if content_for(:header_back_link) %>
            <%= link_to yield(:header_back_link) do %>
              <%= inline_svg_tag "svg/chevron-left.svg", class: "w-6" %>
            <% end %>
          <% else %>
            <%= link_to :back do %>
              <%= inline_svg_tag "svg/chevron-left.svg", class: "w-6" %>
            <% end %>
          <% end %>
        <% end %>

        <% if content_for(:header_right_nav) %>
          <%= yield(:header_right_nav) %>
        <% end %>
      </div>
    <% end %>

    <div class="z-20 mb-5">
      <% if content_for(:header_logo) %>
        <%= image_tag yield(:header_logo), class: "h-20 mx-auto" %>
      <% end %>

      <% if content_for(:header_title) %>
        <h1 class="y-header-title"><%= yield(:header_title) %></h1>
      <% end %>
    </div>

    <% if content_for(:header_main) %>
      <%= yield(:header_main) %>
    <% end %>
  </div>
</div>

app/views/shared/_menu.html.erb
<% if current_user %>
  <div id="dropdown" data-toggle-target="toggleable" class="hidden bg-white text-black overflow-y-auto absolute w-full left-0 z-10 rounded-md space-y-4 p-4">
    <ul class="space-y-2" aria-labelledby="dropdownDefaultButton">
      <li class="flex items-center space-x-3">
        <%= inline_svg_tag "svg/home.svg", class: "w-5" %>
        <%= link_to "Tableau de bord", root_path %>
      </li>
      <li class="flex items-center space-x-3">
        <%= inline_svg_tag "svg/calendar.svg", class: "w-5" %>
        <%= link_to "Évènements", activities_path %>
      </li>
      <li class="flex items-center space-x-3">
        <%= inline_svg_tag "svg/user-circle.svg", class: "w-5" %>
        <%= link_to "Profil", athlete_path(current_user) %>
      </li>
      <% if current_user.admin? && Comment.reported.any? %>
        <li class="flex items-center space-x-3">
          <%= inline_svg_tag "svg/chat.svg", class: "w-5" %>
          <%= link_to "Gestion des commentaires", admin_comments_path %>
        </li>
      <% end %>
      <li class="flex items-center space-x-3">
        <%= inline_svg_tag "svg/logout.svg", class: "w-5" %>
        <%= link_to "Se déconnecter", destroy_user_session_path, data: { turbo_method: :delete } %>
      </li>
    </ul>
  </div>
<% end %>

app/views/shared/_pro_card.html.erb
<div class="flex gap-6 snap-x snap-mandatory overflow-x-auto text-white -mx-5">
  <div class="pl-5 snap-start shrink-0">
    <div class="rounded-lg w-64 h-32 grid grid-cols-5 place-content-center border bg-yaspeez">
      <div class="col-span-2">
        <div class="w-full bg-cover bg-center shrink-0" style="background-image: url(<%= image_path("logo.png") %>);">
        </div>
      </div>
      <div class="col-span-3 space-y-3 uppercase p-2">
        <div class="flex items-center space-x-2 text-xs">
          <span>rate</span>
          <%= inline_svg_tag "svg/star.svg", class: "w-4 text-yellow-500" %>
        </div>
        <div>
          <p class="font-bold uppercase ">SDLC Center</p>
          <p class="text-xs">Salle multisport</p>
        </div>
        <div class="flex items-center space-x-2">
          <%= inline_svg_tag "svg/map-pin.svg", class: "w-4" %>
          <p>distance</p>
        </div>
      </div>
    </div>
  </div>
  <div class="snap-start shrink-0">
    <div class="rounded-lg w-64 h-32 grid grid-cols-5 place-content-center border bg-malachite">
      <div class="col-span-2">
        <div class="w-full bg-cover bg-center shrink-0" style="background-image: url(<%= image_path("logo.png") %>);">
        </div>
      </div>
      <div class="col-span-3 space-y-3 uppercase p-2">
        <div class="flex items-center space-x-2 text-xs">
          <span>rate</span>
          <%= inline_svg_tag "svg/star.svg", class: "w-4 text-yellow-500" %>
        </div>
        <div>
          <p class="font-bold uppercase ">Kady</p>
          <p class="text-xs">Coach</p>
        </div>
        <div class="flex items-center space-x-2">
          <%= inline_svg_tag "svg/map-pin.svg", class: "w-4" %>
          <p>distance</p>
        </div>
      </div>
    </div>
  </div>
  <div class="pr-5 snap-start shrink-0">
    <div class="rounded-lg w-64 h-32 grid grid-cols-5 place-content-center border bg-crimson">
      <div class="col-span-2">
        <div class="w-full bg-cover bg-center shrink-0" style="background-image: url(<%= image_path("logo.png") %>);">
        </div>
      </div>
      <div class="col-span-3 space-y-3 uppercase p-2">
        <div class="flex items-center space-x-2 text-xs">
          <span>rate</span>
          <%= inline_svg_tag "svg/star.svg", class: "w-4 text-yellow-500" %>
        </div>
        <div>
          <p class="font-bold uppercase ">Kady</p>
          <p class="text-xs">Association</p>
        </div>
        <div class="flex items-center space-x-2">
          <%= inline_svg_tag "svg/map-pin.svg", class: "w-4" %>
          <p>distance</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_pro_show.html.erb
<% content_for :header_logo, "logo.png" %>

<% content_for :header_right_nav do %>
  <%= link_to "#", class: "flex flex-col items-center" do %>
    <%= inline_svg_tag "svg/share.svg", class: "w-6" %>
    <p class="text-xs">Suivre</p>
  <% end %>
<% end %>

<% content_for :header_main do %>
  <div class="space-y-3">
    <div class="flex justify-between">
      <div class="flex items-center space-x-2">
        <%= inline_svg_tag "svg/star.svg", class: "w-4" %>
        <span>rate</span>
      </div>
      <div class="flex items-center space-x-2">
        <%= inline_svg_tag "svg/map-pin.svg", class: "w-4" %>
        <span>distance</span>
      </div>
    </div>
    <div class="flex flex-col items-center space-y-2">
      <p class="text-xl font-bold uppercase">SDLC Center</p>
      <p class="text-xs text-center uppercase">address_line_one&nbsp;|&nbsp;address_postal_code address_city</p>
      <%= link_to  "Adhérer", "#", class: "mx-auto flex justify-center border border-white font-semibold w-3/4" %>
    </div>
    <div class="grid grid-cols-4">
      <ul class="col-span-3 list-none text-sm space-y-2">
        <li class="flex items-center space-x-2">
          <%= inline_svg_tag "svg/at.svg", class: "w-4" %>
          <%= link_to "email@email.fr", "mailto:email@email.fr" %>
        </li>
        <li class="flex items-center space-x-2">
          <%= inline_svg_tag "svg/mobile.svg", class: "w-4" %>
          <span>phone_number</span>
        </li>
        <li class="flex items-center space-x-2">
          <%= inline_svg_tag "svg/banknotes.svg", class: "w-4" %>
          <span>prices</span>
        </li>
      </ul>
      <div class="place-self-center">
        <%= link_to "#" do %> 
          <%= inline_svg_tag "svg/map.svg", class: "w-8" %>
        <% end %>
      </div>
    </div>
    <div class="text-sm">
      <p>Description du club</p>
    </div>
  </div>
<% end %>