config/routes.rb
Rails.application.routes.default_url_options[:host] = Rails.application.credentials.dig(:host)
Rails.application.routes.default_url_options[:port] = Rails.application.credentials.dig(:port)

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_for :users

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resource :auth
      resources :users
      resources :notification_tokens, only: :create
    end
  end

  authenticated :user, lambda { |u| u.admin? } do
    namespace :admin do
      resources :comments, only: [:index, :destroy]
    end
  end

  authenticated :user do
    resource :onboarding, only: [:show, :create]

    resources :activities do
      resources :comments, only: [:create, :update], module: :activities do
        resource :reports, only: [:create], module: :comments
      end
      resources :participants, only: [:index, :create, :destroy], module: :activities
    end
    resources :athletes, only: [:show]
    namespace :cities do
      resource :autocomplete, only: [:show]
    end
    resource :dashboard, only: [:show]
    resource :profile, only: [:show, :edit, :update, :destroy]
    resources :sports

    root to: "dashboards#show", as: :user_root
  end

  unauthenticated :user do
    get "/activities", to: "pages#activities"
    get "/profile", to: "pages#profile"
  end

  get "/privacy", to: "pages#privacy"
  get "/terms", to: "pages#terms"

  root to: "pages#home"
end

app/models/activity.rb
# == Schema Information
#
# Table name: activities
#
#  id                             :uuid             not null, primary key
#  address                        :string
#  city_name                      :string
#  country_code                   :string
#  description                    :text
#  duration_in_minutes            :float
#  gender                         :string
#  handisport                     :boolean          default(FALSE)
#  latitude                       :float
#  level                          :string
#  longitude                      :float
#  maximum_participants_number    :integer
#  participants_count             :integer
#  per_participant_price_cents    :integer          default(0), not null
#  per_participant_price_currency :string           default("EUR"), not null
#  postal_code                    :string
#  starts_at                      :datetime
#  created_at                     :datetime         not null
#  updated_at                     :datetime         not null
#  city_id                        :uuid
#  owner_id                       :uuid             not null
#  sport_id                       :uuid             not null
#
# Indexes
#
#  index_activities_on_city_id   (city_id)
#  index_activities_on_owner_id  (owner_id)
#  index_activities_on_sport_id  (sport_id)
#
# Foreign Keys
#
#  fk_rails_...  (city_id => cities.id)
#  fk_rails_...  (owner_id => users.id)
#  fk_rails_...  (sport_id => sports.id)
#
class Activity < ApplicationRecord
  belongs_to :city, optional: true
  belongs_to :owner, class_name: "User"
  belongs_to :sport
  has_many :comments, dependent: :destroy
  has_many :participants, dependent: :destroy
  has_many :users, through: :participants

  geocoded_by :full_address
  reverse_geocoded_by :latitude, :longitude

  monetize :per_participant_price_cents

  scope :handisports, -> { where(handisport: true) }
  scope :future, -> { where("starts_at > ?", DateTime.now) }

  validates :address, presence: true
  validates :city_name, presence: true
  validates :description, presence: true
  validates :duration_in_minutes, presence: true
  validates :gender, presence: true
  validates :level, presence: true
  validates :maximum_participants_number, presence: true
  validates :per_participant_price_cents, presence: true
  validates :sport_id, presence: true
  validates :starts_at, presence: true

  GENDERS =
    [
      { code: "mixte", name: "Mixte" },
      { code: "femme", name: "Femme" },
      { code: "homme", name: "Homme" },
    ]

  LEVELS =
    [
      { code: "Pas de niveau", name: "Pas de niveau" },
      { code: "Tous niveaux", name: "Tous niveaux" },
      { code: "Débutant", name: "Débutant" },
      { code: "Confirmé", name: "Confirmé" },
      { code: "Expert", name: "Expert" },
    ]

  MINIMUM_DISTANCE_IN_KM = 0
  MAXIMUM_DISTANCE_IN_KM = 50

  def calculate_coordinates
    results = Geocoder.search([address, city].join(" "))

    if results.any?
      most_accurate_result = results.first

      self.latitude = most_accurate_result.latitude
      self.longitude = most_accurate_result.longitude

    elsif self.city.present?
      self.latitude = self.city.latitude
      self.longitude = self.city.longitude
      self.postal_code = self.city.code_postal

    else
      results = Geocoder.search(city)

      if results.any?
        most_accurate_result = results.first

        self.latitude = most_accurate_result.latitude
        self.longitude = most_accurate_result.longitude
      end
    end

    self
  end

  def full_address
    [address, postal_code, city].join(" ")
  end

  def self.genders_select_for
    genders = Activity::GENDERS
    genders.map { |gender| [gender[:name], gender[:code]] }
  end

  def self.levels_select_for
    levels = Activity::LEVELS
    levels.map { |level| [level[:name], level[:code]] }
  end

  def self.next
    future.order(:starts_at)&.first
  end

  def participable?
    maximum_participants_number > participants_count
  end

  def per_participant_price_euros
    if per_participant_price_cents
      per_participant_price_cents / 100
    end
  end
end

app/controllers/activities/application_controller.rb
# frozen_string_literal: true

class Activities::ApplicationController < ApplicationController
  before_action :set_activity

  private

  def set_activity
    @activity = Activity.find(params[:activity_id])
  end
end

app/controllers/activities/comments/reports_controller.rb
# frozen_string_literal: true

module Activities
  module Comments
    class ReportsController < ApplicationController
      before_action :set_comment, only: %i[ create ]

      def create
        @comment.reported_at = DateTime.now
        @comment.reported_by = current_user
        authorize [:activity, @comment]

        if @comment.save
          User.admins.each do |admin|
            # TODO: Change to deliver_later
            ReportActivityCommentNotification.with(activity: @activity).deliver(admin)
          end
          redirect_to activity_path(@activity), notice: "Signalement effectué avec succès."
        else
          redirect_to activity_path(@activity), alert: "Une erreur s'est produite lors de votre signalement. Veuillez réessayer."
        end
      end

      private

      def set_comment
        @comment = Comment.find(params[:comment_id])
      end
    end
  end
end

app/controllers/activities/comments_controller.rb
# frozen_string_literal: true

module Activities
  class CommentsController < ApplicationController
    before_action :set_comment, only: %i[ update destroy ]

    # POST /comments or /comments.json
    def create
      @comment = @activity.comments.new(comment_params)
      authorize [:activity, @comment]

      @comment.author = current_user

      respond_to do |format|
        if @comment.save
          # TODO: Change to deliver_later
          ActivityCommentNotification.with(activity: @activity).deliver(@activity.owner)
          format.html { redirect_to activity_path(@activity), notice: "Commentaire ajouté avec succès." }
          format.json { render :show, status: :created, location: @comment }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /comments/1 or /comments/1.json
    def update
      respond_to do |format|
        if @comment.update(comment_params)
          format.html { redirect_to activity_path(@activity), notice: "Commentaire modifié avec succès." }
          format.json { render :show, status: :ok, location: @comment }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /comments/1 or /comments/1.json
    def destroy
      @comment.destroy

      respond_to do |format|
        format.html { redirect_to activity_path(@activity), notice: "Commentaire supprimé avec succès." }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
      authorize [:activity, @comment]
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body)
    end
  end
end

app/controllers/activities/participants_controller.rb
# frozen_string_literal: true

module Activities
  class ParticipantsController < ApplicationController
    def index
      @participants = @activity.participants
      authorize [:activity, @participants]
    end

    def create
      @participation = @activity.participants.new(
        user: current_user,
      )
      authorize [:activity, @participation]

      if @participation.save
        # TODO: Change to deliver_later
        ActivityRegistrationNotification.with(activity: @activity).deliver(@activity.owner)
        redirect_to @activity, notice: "Vous êtes inscrit avec succès à cette activité !"
      else
        redirect_to @activity, alert: "Une erreur s'est produite lors de votre inscription à cette activité."
      end
    end

    def destroy
      @participation = @activity.participants.find_by(user: current_user)
      authorize [:activity, @participation]

      if @participation.destroy
        redirect_to @activity, notice: "Vous vous êtes désinscrit avec succès de cette activité."
      else
        redirect_to @activity, alert: "Une erreur s'est produite lors de votre désinscription à cette activité."
      end
    end
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: %i[ show edit update destroy ]

  # GET /activities or /activities.json
  def index
    if params[:distance].present?
      @distance = params[:distance].to_i
      @distance = [Activity::MINIMUM_DISTANCE_IN_KM, @distance].max
      @distance = [@distance, Activity::MAXIMUM_DISTANCE_IN_KM].min
    else
      @distance = 10
    end
    @sport = Sport.find(params[:sport_id]) if params[:sport_id].present?
    @handisport = params[:handisport].eql?("1")

    activities = Activity.future.order(starts_at: :asc).near([current_user.latitude, current_user.longitude], @distance, units: :km)
    activities = activities.where(sport: @sport) if @sport.present?
    activities = activities.handisports if @handisport

    @pagy, @activities = pagy(activities)

    authorize @activities
  end

  # GET /activities/1 or /activities/1.json
  def show
    @participants = @activity.participants
    @comments = @activity.comments
    @new_comment = Comment.new(activity: @activity)
  end

  # GET /activities/new
  def new
    @activity = Activity.new
    authorize @activity

    if params[:sport_id].present?
      @activity.sport = Sport.find(params[:sport_id])
    end
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities or /activities.json
  def create
    @activity = current_user.organized_activities.new(activity_params)
    authorize @activity

    @activity.calculate_coordinates
    @activity.participants.new(user: current_user)

    respond_to do |format|
      if @activity.save
        # TODO: Notify prospective participants
        format.html { redirect_to activity_url(@activity), notice: "L'activité a été créée avec succès !" }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1 or /activities/1.json
  def update
    @activity.assign_attributes(activity_params)
    @activity.calculate_coordinates

    respond_to do |format|
      if @activity.save
        format.html { redirect_to activity_url(@activity), notice: "L'activité a été mise à jour avec succès !" }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1 or /activities/1.json
  def destroy
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url, notice: "L'activité a été supprimée avec succès." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_activity
    @activity = Activity.find(params[:id])
    authorize @activity
  end

  # Only allow a list of trusted parameters through.
  def activity_params
    params.require(:activity).permit(
      :address,
      :city_id,
      :city_name,
      :description,
      :duration_in_minutes,
      :gender,
      :handisport,
      :level,
      :maximum_participants_number,
      :participants_count,
      :per_participant_price,
      :starts_at,
      :sport_id,
    )
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_activity.html.erb
<%= link_to activity_path(activity) do %>
  <div class="bg-cover bg-center rounded-xl w-full h-64 shadow-xl" style="background-image: url(<%= url_for(activity.owner.avatar.present? ? activity.owner.avatar : "" ) %>);">
    <div class="text-white h-full w-full flex flex-col justify-end rounded-lg bg-gradient-to-t from-gray-500/[0.75] to-gray-500/[0.15]" >
      <div class="p-4">
        <div class="flex items-center space-x-2">
          <h2 class="uppercase font-semibold text-xl">
            <%= activity.owner.nickname %>
          </h2>
        </div>
        <div class="flex items-center space-x-2">
          <%= inline_svg_tag "svg/trophy.svg", class: "w-6 shrink-0 text-yellow-500" %>
          <span class="text-sm truncate"><%= activity.sport.name %></span>
        </div>
        <% if activity.handisport? %>
          <div class="flex items-center space-x-2">
            <%= inline_svg_tag "svg/handisport.svg", alt: "Icône Handisport", class: "w-6 shrink-0" %>
            <span class="text-sm truncate">Handisport</span>
          </div>
        <% end %>
        <div class="flex items-center space-x-2">
          <%= inline_svg_tag "svg/map-pin.svg", class: "w-6 shrink-0" %>
          <span class="text-sm font-medium truncate"><%= activity.city_name %></span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/activities/_event_card.html.erb
<%= link_to activity_path(activity) do %>
  <div class="bg-white shadow-md rounded-md divide-y divide-gray-200 overflow-hidden text-xs cursor-pointer">
    <div class="py-2 px-4 flex flex-col space-y-3">
      <div class="flex items-center space-x-3">
        <div class="bg-cover bg-center rounded-full w-12 h-12  shrink-0" style="background-image: url(<%= url_for(activity.owner.avatar.present? ? activity.owner.avatar : "" ) %>);">
        </div>
        <span class="text-xl"><%= activity.owner.nickname %></span>
      </div>
      <span class="text-base"><%= activity.sport.name %></span>
      <div class="flex items-center space-x-2">
        <%= inline_svg_tag "svg/clock.svg", class: "w-4 shrink-0" %>
        <span><%= activity.starts_at.strftime("%d/%m/%Y - %Hh%M") %></span>
      </div>
    </div>
    <div class="px-4 py-1 flex items-center space-x-2">
      <%= inline_svg_tag "svg/map-pin.svg", class: "w-4 shrink-0" %>
      <div class="flex flex-col">
        <span class="font-bold"><%= activity.address %></span>
        <span><%= activity.postal_code %> <%= activity.city_name %></span>
      </div>
    </div>
  </div>
<% end %>

app/views/activities/edit.html.erb
<% content_for :header_title, "Modifier l'activité" %>

<main class="y-card-main">
  <%= render "form", activity: @activity %>
</div>

app/views/activities/index.html.erb
<% content_for :header_logo, "logo.png" %>
<% content_for :header_title, "Sports à proximité" %>
<% content_for :header_back_link, dashboard_path %>

<% content_for :header_main do %>
  <div class="flex justify-center">
    <%= link_to "J'organise une activité", new_activity_path(sport_id: @sport&.id), class: "y-btn y-btn-white" %>
  </div>
<% end %>

<div class="y-card-main space-y-5">
  <%= form_with(url: activities_path, method: :get, class: "space-y-2") do |form| %>
    <div class="flex space-x-2 items-center">
      <%= form.label "Sport", class: "y-label" %>
      <%= form.collection_select :sport_id, Sport.all, :id, :name, { selected: @sport&.id, prompt: "Sélectionnez un sport" }, data: { controller: "slim" }, class: "w-full" %>
    </div>
    <div class="flex space-x-2 items-center" data-controller="distance">
      <%= form.label :distance, "Distance", class: "y-label" %>
      <%= form.range_field :distance, min: 0, max: 50, value: @distance, step: 5, class: "w-full h-2 rounded-lg appearance-none cursor-pointer bg-yaspeez", data: { "distance-target": "rangeField", action: "input->distance#changeRange"}%>
      <p data-distance-target="showDistance"><%= @distance %>km</p>
      <%= form.button class: "y-btn y-btn-yaspeez-blue" do %>
        <%= inline_svg_tag "svg/search.svg", class: "w-6" %>
      <% end %>
    </div>
    <div class="flex space-x-2 items-center">
      <%= form.label :handisport, "Handisport", class: "y-label" %>
      <%= form.check_box :handisport, checked: @handisport, class: "y-form" %>
    </div>
  <% end %>

  <% if @activities.present? %>
    <ul class="list-none grid grid-cols-2 gap-4 -mx-5 p-5 bg-gradient-to-t from-white-500 to-transparent">
      <% @activities.each do |activity| %>
        <%= render "activity", activity: %>
      <% end %>
    </ul>
  <% else %>
    <div class="flex justify-center items-center text-sm italic space-x-2">
      <%= inline_svg_tag "svg/face-frown.svg", class: "w-5 shrink-0" %>
      <% if @sport.eql?(current_user.sport) %>
        <p>Aucune activité de votre sport favori à <%= @distance %> km autour de chez vous.</p>
      <% elsif @sport.present? %>
        <p><%= @sport.name %> : aucune activité à <%= @distance %> km autour de chez vous !</p>
      <% else %>
        <p>Aucune activité à <%= @distance %> km autour de chez vous !</p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/activities/new.html.erb
<% content_for :header_title, "Nouvelle activité" %>

<main class="y-card-main">
  <%= render "form", activity: @activity %>
</main>

app/views/activities/show.html.erb
<% content_for :header_title, @activity.sport.name %>
<% content_for :header_back_link, activities_path %>
<% content_for :header_main do %>
  <div class="flex flex-col items-center justify-center">
    <p class="italic font-light"><%= @activity.level %></p>
  </div>
<% end %>

<div class="y-card-main space-y-5">
  <div>
    <% if current_user.eql?(@activity.owner) %>
      <div class="flex justify-center">
        <span class="flex-shrink-0 rounded-full bg-green-100 py-1 px-2 text-sm font-medium text-green-800">J'organise</span>
      </div>
    <% else %>
      <p>Activité organisée par</p>
      <div class="flex items-center space-x-4">
        <div class="bg-cover bg-center rounded-full w-14 h-14 shrink-0" style="background-image: url(<%= url_for(@activity.owner.avatar) if @activity.owner.avatar.attached? %>);"></div>
        <div class="flex flex-col">
          <span class="text-gray-500"><%= @activity.owner.nickname %></span>
          <%= link_to "Voir le profil", athlete_path(@activity.owner), class: "text-blue-500 underline" %>
        </div>
      </div>
    <% end %>
  </div>
  <ul class="list-none text-sm space-y-2 -mx-5 p-5 bg-white">
    <li class="flex items-center space-x-2">
      <%= inline_svg_tag "svg/clock.svg", class: "w-4" %>
      <span><%= l(@activity.starts_at, format: "%A %d/%m/%Y - %Hh%M").capitalize %></span>
    </li>
    <li class="flex items-center space-x-2">
      <%= inline_svg_tag "svg/map-pin.svg", class: "w-4" %>
      <div class="flex flex-col">
        <span><%= @activity.address %></span>
        <span><%= @activity.postal_code %> <%= @activity.city_name %></span>
      </div>
    </li>
    <% if @activity.handisport? %>
      <li class="flex items-center space-x-2">
        <%= inline_svg_tag "svg/handisport.svg", class: "w-4" %>
        <span>Activité handisport</span>
      </li>
    <% end %>
    <li class="flex items-center space-x-2">
      <%= inline_svg_tag "svg/user-circle.svg", class: "w-4" %>
      <span>Genre&nbsp;: <%= @activity.gender %></span>
    </li>
    <li class="flex flex-col <%= "space-y-2" if @activity.participants.count > 0 %>">
      <div class="flex justify-between">
        <div class="flex items-center space-x-2">
          <%= inline_svg_tag "svg/user-group.svg", class: "w-4" %>
          <span>Participants&nbsp;: <%= @activity.participants.count %> / <%= @activity.maximum_participants_number %></span>
        </div>
        <%= link_to activity_participants_path(@activity), class: "flex space-x-2" do %>
          <span class="italic text-sm">Voir plus</span>
          <%= inline_svg_tag "svg/chevron-right.svg", class: "w-4" %>
        <% end %>
      </div>
      <ul class="list-none flex space-x-1">
        <% @participants.first(5).each do |participant| %>
          <li class="bg-cover bg-center rounded-full w-8 h-8 shrink-0" style="background-image: url(<%= url_for(participant.user.avatar.present? ? participant.user.avatar : "" ) %>);"></li>
        <% end %>
      </ul>
    </li>
    <li class="flex items-center space-x-2">
      <%= inline_svg_tag "svg/banknotes.svg", class: "w-4" %>
      <span>Tarif par participant&nbsp;: <%= number_to_euro(@activity.per_participant_price_euros) %></span>
    </li>
  </ul>
  <% if current_user.id.in?(@activity.participants.pluck(:user_id)) %>
    <div class="grid grid-cols-2 gap-4 items-center">
      <div class="<%= "col-span-2" if current_user.eql?(@activity.owner) %>">
        <%= link_to "https://maps.apple.com/?daddr=#{@activity.address},#{@activity.postal_code},#{@activity.city_name}&dirflg=d&t=h", class:"y-btn-icon y-btn-yaspeez-blue" do %>
          <%= inline_svg_tag "svg/map.svg", class: "w-5" %>
          <span>M'y rendre</span>
        <% end %>
      </div>
      <div class="<%= "hidden" if current_user.eql?(@activity.owner) %>">
        <%= link_to activity_participant_path(@activity, current_user), data: { turbo_method: :delete, turbo_confirm: "Êtes-vous sûr de vouloir vous désinscrire de cette activité ?" }, class:"y-btn-icon y-btn-yaspeez-blue" do %>
          <%= inline_svg_tag "svg/user-minus.svg", class: "w-5" %>
          <span>Me désinscrire</span>
        <% end %>
      </div>
    </div>
  <% else %>
    <div>
      <%= form_with(model: [@activity, @activity.participants.new], class: "contents") do |form| %>
        <%= form.button class: "y-btn-icon y-btn-yaspeez-blue" do %>
          <%= inline_svg_tag "svg/user-plus.svg", class: "w-5" %>
          <span>M'inscrire</span>
        <% end %>
      <% end %>
    </div>
  <% end %>

  <div class="-mx-5 p-5 bg-white text-sm">
    <p class="italic"><span class="font-bold">Description&nbsp;:</span> <%= @activity.description %></p>
  </div>
  <div class="space-y-3 text-sm">
    <span class="italic font-bold">Commentaires</span>
    <% if @comments.count.eql?(0) %>
      <div>
        <p class="text-center italic font-light">Il n'y a pas encore de commentaire</p>
      </div>
    <% else %>
      <div class="divide-y">
        <% @comments.each do |comment| %>
          <div class="flex justify-between items-center py-2">
            <div class="flex space-x-2">
              <div class="bg-cover bg-center rounded-full w-9 h-9 shrink-0" style="background-image: url(<%= url_for(comment.author.avatar.present? ? comment.author.avatar : "" ) %>);"></div>
              <div>
                <p><span class="font-bold"><%= comment.author.nickname %></span> <span class="font-light text-xs italic">(il y a <%= time_ago_in_words(comment.created_at) %>)</span>&nbsp;:</p>
                <%= comment.body %>
              </div>
            </div>
            <% if current_user.admin? %>
              <%= link_to admin_comment_path(comment), data: { turbo_method: :delete, turbo_confirm: "Êtes-vous sûr de vouloir supprimer ce commentaire ?" } do %>
                <%= inline_svg_tag "svg/trash.svg", class: "w-5 text-red-500" %>
              <% end %>
            <% else %>
              <%= link_to activity_comment_reports_path(@activity, comment), data: { turbo_method: :post, turbo_confirm: "Êtes-vous sûr de vouloir signaler ce commentaire ?" } do %>
                <%= inline_svg_tag "svg/flag.svg", class: "w-5 text-red-500" %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
    <%= form_with(model: [@activity, @new_comment], class:"grid grid-cols-5 gap-2") do |form| %>
      <%= form.text_area :body, placeholder: "Ajoutez votre commentaire ici...", required: true, class: "y-form-border col-span-4" %>
      <%= form.button class: "y-btn-icon y-btn-yaspeez-blue" do %>
        <%= inline_svg_tag "svg/send.svg", class: "w-5" %>
      <% end %>
    <% end %>
  </div>
  <% if current_user.eql?(@activity.owner) %>
    <div class="grid grid-cols-2 gap-4 items-center">
      <%= link_to edit_activity_path(@activity), class: "y-btn-icon y-btn-white" do %>
        <%= inline_svg_tag "svg/edit.svg", class: "w-5" %>
        <span>Modifier</span>
      <% end %>
      <%= button_to activity_path(@activity), method: :delete, data: { turbo_confirm: "Êtes-vous sûr de vouloir supprimer cette activité ?" }, class: "y-btn-icon y-btn-red" do %>
        <%= inline_svg_tag "svg/trash.svg", class: "w-5" %>
        <span>Supprimer</span>
      <% end %>
    </div>
  <% end %>
</div>